choco install dotnetcore-sdk --version 2.0.3
choco install dotnetcore-sdk --version 2.1.105
choco install dotnetcore-sdk --version 2.1.200
choco install dotnetcore-sdk --version 2.1.300
choco install dotnetcore-sdk --version 2.1.301
choco install dotnetcore-sdk --version 2.1.302
choco install dotnetcore-sdk --version 2.1.403
choco install dotnetcore-sdk --version 2.1.500
choco install dotnetcore-sdk --version 2.2.0