gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]

image_build_task:
  auto_cancellation: false
  gce_instance:
    image_project: ubuntu-os-cloud
    image_name: ubuntu-minimal-1604-xenial-v20181203
    zone: europe-west3-a
    preemptible: false
    cpu: 6
    memory: 15G
    disk: 128
    use_ssd: true
  env:
    ACCOUNT: ENCRYPTED[!e7ca0841e1d1242ca4f8a3a5937eb79d9217ad280700f50cc2f6f82f07ca1be9a471e24763ed81eed44a6096005cefcb!]
  timeout_in: 180m
  build_script: bash build-packer-image.sh

test_windows_task:
  depends_on:
   - image_build
  gce_instance:
    image_project: language-team
    image_family: lt-base-windows-dotnet
    platform: windows
    zone: europe-west3-a
    preemptible: true
    cpu: 2
    memory: 8G
    disk: 128
  git_script: git --version
  java_script: java -version
  scanner_script: C:\sonar-scanner-4.0.0.1744\bin\sonar-scanner.bat --version
  mvn_script: mvn --version
  msbuild_script: MSBuild.exe -version
  dotnet_script: dotnet --version
  dotnet_list_sdks_script: dotnet --list-sdks
  nodejs_script: node --version
  buildTools_script: bash -c "cat /c/buildTools-docker/bin/cirrus-env"
  script:
    - dir c:\
    - dir c:\buildTools-docker\bin
    - echo %PATH%

