gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]

task:
  #only_if: false
  auto_cancellation: false
  gce_instance:
    image_project: ubuntu-os-cloud
    image_name: ubuntu-minimal-1804-bionic-v20190204b
    zone: europe-west3-a
    preemptible: false
    cpu: 6
    memory: 30G
    disk: 20

  env:
    ACCOUNT: ENCRYPTED[!0bacf9b92a239fe906a2e58e03b0376177b48c31a54b0d0c9488bdb00b318bbf6684c0a938f5f38ed2e0dd8499eaff88!]
  timeout_in: 60m
  matrix:
    - { env: { TEMPLATE_NAME: linux_java } }
  name: ${TEMPLATE_NAME}
  build_script:
    - apt update && apt -y install curl unzip
    - curl -LsS https://releases.hashicorp.com/packer/1.3.5/packer_1.3.5_linux_amd64.zip > packer.zip
    - unzip packer.zip
    - echo ${ACCOUNT} > account.json
    - GOOGLE_APPLICATION_CREDENTIALS=account.json ./packer build -force linux/${TEMPLATE_NAME}.json

dotnet_windows_build_task:
  #only_if: false
  auto_cancellation: false
  gce_instance:
    image_project: ubuntu-os-cloud
    image_name: ubuntu-minimal-1604-xenial-v20181203
    zone: europe-west3-a
    preemptible: false
    cpu: 6
    memory: 15G
    disk: 60
  env:
    ACCOUNT: ENCRYPTED[!0bacf9b92a239fe906a2e58e03b0376177b48c31a54b0d0c9488bdb00b318bbf6684c0a938f5f38ed2e0dd8499eaff88!]
  timeout_in: 180m
  build_script:
    - apt-get update && apt-get -y install curl unzip
    - curl -LsS https://releases.hashicorp.com/packer/1.3.5/packer_1.3.5_linux_amd64.zip > packer.zip
    - unzip packer.zip
    - echo ${ACCOUNT} > account.json
    - GOOGLE_APPLICATION_CREDENTIALS=account.json ./packer build -force windows/windows-dotnet.json

test_windows_task:
  #only_if: false
  depends_on:
   - dotnet_windows_build
  gce_instance:
    image_project: language-team
    image_name: windows-dotnet
    platform: windows
    zone: europe-west3-a
    preemptible: true
    cpu: 2
    memory: 8G
    disk: 100
  git_script: git --version
  java_script: java -version
  scanner_script: C:\sonar-scanner-4.0.0.1744\bin\sonar-scanner.bat --version
  python_script: python.exe --version
  node_script: node --version
  npm_script: npm --version
  script: 
    - dir c:\


test_linux_java_task:
  #only_if: false
  auto_cancellation: false
  #depends_on:
  #  - linux_java
  gce_instance:
    image_project: language-team
    image_name: linux-java
    zone: europe-west3-a
    preemptible: true
    cpu: 1
    memory: 1G
    disk: 10
  git_script: git --version
  java_script: java -version
  scanner_script: 
    - source /etc/profile
    - sonar-scanner --version
  python_script: python --version
  node_script: node --version
  npm_script: npm --version
  ant_script: ant -version
  mvn_script: mvn --version  
  filebeat_script: filebeat version
  script:
    - echo $SHELL    
    - source /etc/profile
    - sdk list java
    - sdk default java 12.0.2-zulu
    - java -version
    - ls /opt
    - sudo grep -r 'APT::Periodic::Update-Package-Lists' /etc
  