gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]
                    
docker_build_task:
  gce_instance:
    image_project: language-team
    image_name: docker-builder-lt-v1
    zone: us-central1-a
    disk: 10
    cpu: 1
    memory: 1G
    preemptible: false
  
  build_script:
    - docker pull gcr.io/language-team/base:v1 
    - docker build -f languageTeam.Dockerfile -t base .
    - docker tag base "gcr.io/language-team/base:v1"
    - docker push "gcr.io/language-team/base:v1"